### PR TITLE
Tabs for Phases section

### PR DESCRIPTION
**Pull request by davidrnovak**
- Refactor Phases section on homepage to a tab-style element

### Before
Screen Shot 2022-12-15 at 8 53 06 AM

### After
Screen Shot 2022-12-15 at 8 37 51 AM

Screen Shot 2022-12-15 at 8 41 40 AM

### CODE REVIEW

**Comment by cpytel** [comment]
@davidrnovak At full screen browser width on my 14" macbook pro the items wrap:

Screenshot 2022-12-15 at 12 19 24

I think this is a reasonable browser width, so we probably want to tighten this up?

**Comment by cpytel** [comment]
Could a potential quick fix strategy be to not include Planning and potentially Analyize in the list with the same way as the others?

**Comment by cpytel** [comment]
I think its a bit of an issue on mobile that when you click on an item, because the other tab being shown closes, what is in your viewport switches and the content for the item you clicked on is no longer visible.

To replicate this, on mobile click on Analyze. The Analyze content is mostly off my screen when I do that.

**Comment by davidrnovak** [comment]
@cpytel I think removing Planning and Analyze currently is the best option. The phase overview does say 5 phases (I just overlooked it), so having the 5 phases makes sense for consistency.

For the mobile issue I just want to make sure I'm understanding it correctly. Are we wanting the tab, when clicked, to snap the content to the top of the viewport?

**Pull request merged**
